markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: PointlessRants.com
url: http://pointlessrants.com
baseurl: ''
description: Technobable!
twitter: daspecster
github: daspecster
gravatar_url: http://www.gravatar.com/avatar/bb77eb91c2d8a076f7844800702e543e
